### ISSUE TITLE
Wrong pixels height size in iframe

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#92] opened 2018-09-19 16:13 UTC
Hi there-
I am using latest version of ShinyProxy 2.0.3 and while using endpoint way (i.e. app_direct/ path) I have no issue with the display, using iframe way (i.e. app/ path) the height computed is not right - it is giving me 937px instead of 943px in the tag below:
`<iframe id="shinyframe" src="/endpoint/9a8b1ca1-4f7f-423a-bc0f-73e6b916e358/" width="100%" frameborder="0" style="height: 937px;"></iframe>`

How can I do so the height gets correctly calculated ?
I have attached grabs, one with the wrong height (the default one) and another one with the right one (that I manually edit in Chrome developer tools).

**wrong height by default:**
![1](https://user-images.githubusercontent.com/4976433/45766307-d7b64700-bbfc-11e8-9dbc-f743d66739cc.png)
**then edit the attributes myself:**
![3](https://user-images.githubusercontent.com/4976433/45766305-d7b64700-bbfc-11e8-8f00-91f858394842.png)
**which makes the height now correct:**
![2](https://user-images.githubusercontent.com/4976433/45766306-d7b64700-bbfc-11e8-8390-9a5f18ccb725.png)

Any idea ? Thanks guys.

**Comment by fmichielssen** [comment] 2018-09-21 11:38
Hi @dylancis,

I suspect this is the cause of the 6 pixel difference:
https://github.com/openanalytics/shinyproxy/blob/692663e4804fe6d907d9cf68839f106249d8ad0e/src/main/resources/templates/app.html#L42
I believe this size adjustment was done to prevent unnecessary scrollbars from appearing, but it looks like it causes unwanted side-effects.

**Comment by dylancis** [comment] 2018-09-21 16:53
Hi @fmichielssen-
Understood, we looked into this and I don't think the `-6px` are necessary.
You could set the attribute ` display: block` on the iframe component and the 
both the scrollbar goes away and height is correct.

Thanks, Dylan

**Comment by tverbeke** [comment] 2018-09-22 16:42
Thanks; https://github.com/openanalytics/shinyproxy/commit/38abfa3f972387da77c6c17f2ea9bb03729c2c42 implements the fix which has been released in ShinyProxy 2.0.4.

**Closed by tverbeke** 2018-09-22 16:42 UTC
