### ISSUE TITLE
Unable to Upload file using fileInput Method Not Allowed

### ISSUE THREAD

**Issue by creiche** [openanalytics/shinyproxy#141] opened 2019-03-28 20:35 UTC
When trying to upload a file through ShinyProxy to a shiny app using a fileInput, we receive:

Error

Status code: 405
Message: Method Not Allowed
Stack Trace: n/a

ShinyProxy logs show:

2019-03-28 20:12:15.615 DEBUG 1 --- [  XNIO-2 task-4] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/app_direct/shiny-mkt-campaign-recommendations/session/43b642bdfe4ca8a30f87b33c66d57200/upload/6ecc2cdeea2fc3052a0e00aa]
  | 2019-03-28 20:12:15.615 DEBUG 1 --- [  XNIO-2 task-4] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /app_direct/shiny-mkt-campaign-recommendations/session/43b642bdfe4ca8a30f87b33c66d57200/upload/6ecc2cdeea2fc3052a0e00aa
  | 2019-03-28 20:12:15.616 DEBUG 1 --- [  XNIO-2 task-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
  | 2019-03-28 20:12:15.616 DEBUG 1 --- [  XNIO-2 task-4] .w.s.m.a.ResponseStatusExceptionResolver : Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
  | 2019-03-28 20:12:15.616 DEBUG 1 --- [  XNIO-2 task-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
  | 2019-03-28 20:12:15.616  WARN 1 --- [  XNIO-2 task-4] o.s.web.servlet.PageNotFound             : Request method 'POST' not supported

**Comment by shrektan** [comment] 2019-03-29 01:43
I believe it's duplicate of #140 . For now you can the previous release of ShinyProxy, a.k.a, version 2.1.0, which should work fine.

**Comment by tverbeke** [comment] 2019-03-29 20:28
@creiche ... and from now on you can also use ShinyProxy 2.2.1 (which contains a fix for this).

**Closed by tverbeke** 2019-03-29 20:28 UTC
