### ISSUE TITLE
Recive additional info from web auth server

### ISSUE THREAD

**Issue by kuzmenkov111** [openanalytics/shinyproxy#231] opened 2020-09-14 21:20 UTC
Hi there!
Many Thanks for Web server Auth feature. It is absolutely great!

But is it possible to add some function with the following workflow:

1) ShinyProxy sent the http request to Auth Web server ------>
2) Auth Web server answers 200 OK. Plus Auth Web Server sends 
`shinyproxy_json_field {
some string…
} ` 
3) ShinyProxy authorizes user + receive `shinyproxy_json_field` and sends it into container as ENV SHINYPROXY_OPTIONS (just string env, and shiny app developers may use f.e. jsonlite R package to parse this ENV and use different arguments from this ENV).

I suppose this feature greatly improves functionality and interaction between Auth Web Server and Shiny app with small cost (just get custom json field and sent it into container ENV).

Thank you for your amazing solution!

**Comment by kuzmenkov111** [comment] 2021-03-03 14:59
Dear @LEDfan 

Do you have any plans for implementing this feature?

**Comment by LEDfan** [comment] 2021-07-30 13:06
Duplicate of #162

Hi @kuzmenkov111 I just noticed you already create a very similar issue :P 

I was aware of your feature request, and I understand the use-case, but currently we have no plans to implement it.
(I'm keeping the other issue open as feature request)

**Closed by LEDfan** 2021-07-30 13:06 UTC
Labels: enhancement

**Comment by kuzmenkov111** [comment] 2021-12-01 10:05
I'm looking forward to this feature. Many thanks!!!
