### ISSUE TITLE
Cannot open multiple RShiny App simulatenously

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#481] opened 2024-03-08 11:03 UTC
Hi @tverbeke -
Since the upgrade to `3.0.2` I cannot open multiple same `RShiny` app in multipe tabs which I always used to do that (even though the R kernel could only run one thread at the time). I don't have the issue with `Dash` app, I can open as many as I want.

The behaviour is that when I open a second tab using `RShiny`, the first one already opened stopped:
![image](https://github.com/openanalytics/shinyproxy/assets/4976433/e6454839-ffd8-4065-9d62-ff8292694693)
And the console shows:
![image](https://github.com/openanalytics/shinyproxy/assets/4976433/743e0002-efd0-4415-9a6d-ffcfb46c1888)

Can you please tell me if there was something change in that newer version that is causing that?

**Comment by LEDfan** [comment] 2024-03-11 08:07
Hi @dylancis 

This should still be possible in version 3.0.2. Which version were you using previously?
The error message indicates that the websocket connection was closed, this could be caused because the Shiny app runs into an error. Can you check the logs/output of the shiny app? In addition can you also check and post the ShinyProxy logs?

**Comment by dylancis** [comment] 2024-03-11 10:03
Thanks @LEDfan , this was indeed my undersatanding as per our conversation here: https://github.com/openanalytics/shinyproxy/issues/397

Before we were using `2.6.1`, we have 3 apps in Dash hosted in ShinyProxy and 3 RShiny, the 3 RShiny app have now the same issue. The app-logs do not contains anything once the app shut down - which makes me believe this is coming from ShinyProxy itself. Note that configuration of the app (YAML) has not changed following the upgrade.

It seems somehow related to this one https://support.openanalytics.eu/t/unexpected-and-unpredictable-shiny-app-terminations-with-shinyproxy/2661

Please find attached the log of Shinyproxy where you can the error `UT001000`
[logs-insights-results.json](https://github.com/openanalytics/shinyproxy/files/14556734/logs-insights-results.json)

**Comment by LEDfan** [comment] 2024-03-11 11:55
Since you are only having the issue with Shiny apps and the issue is caused by an asset failing to load, I suspect that you are experiencing the issue described here: https://shinyproxy.io/faq/#the-assets-of-my-shiny-app-sometimes-fail-to-load-http-error-503

Can you try installing Shiny using the above method? Please make sure to not have any other command in your Dockerfile that install shiny (e.g. if you currently have `install.packages('shiny')` somewhere, you need to remove that line.

**Comment by dylancis** [comment] 2024-03-12 11:56
Thanks for your suggestion @LEDfan . However I don't think this is related to that.

We have reverted back to `2.6.1` today - using the same app and the same R-base image, only `ShinyProxy jar` version changed and the issue is now gone in `2.6.1`.

**Comment by dylancis** [comment] 2024-03-19 08:25
> Since you are only having the issue with Shiny apps and the issue is caused by an asset failing to load, I suspect that you are experiencing the issue described here: https://shinyproxy.io/faq/#the-assets-of-my-shiny-app-sometimes-fail-to-load-http-error-503
> 
> Can you try installing Shiny using the above method? Please make sure to not have any other command in your Dockerfile that install shiny (e.g. if you currently have `install.packages('shiny')` somewhere, you need to remove that line.

@LEDfan  I did what you suggested, please find attached the `Dockerfile`, and the issue remains. `2.6.1` is still working fine though.
[Dockerfile.txt](https://github.com/openanalytics/shinyproxy/files/14647619/Dockerfile.txt)

**Comment by dylancis** [comment] 2024-04-04 15:43
I noticed that while in `2.6.1` the `ShinySession` returned the url as 
```
http://shiny-dev.cr0a68f.easn.morningstar.com/app_direct_i/eurmbsinsight
```

The `3.0.2` version returns is differenty:
```
http://shiny-prod.crcc2f9.eas.morningstar.com/app_proxy/3293fede-ab92-4b5b-8a08-5df4722fd622
```

Could that be the reason?

**Comment by dylancis** [comment] 2024-05-07 10:28
Hi @LEDfan  should I try with 3.1.0 version see if the issue for resolved ? Thanks

**Comment by LEDfan** [comment] 2024-05-07 13:29
Hi @dylancis unfortunately, I was not able to re-produce your issue, so the release does not include a fix specific to this issue. However, it contains various improvements, that might solve this issue, so it would be good to try it out and know whether it's fixed.

**Comment by LEDfan** [comment] 2024-05-14 15:10
Hi @dylancis I continued looking into this and found a potential fix. Could you please try using image `openanalytics/shinyproxy-snapshot:3.1.0-20240514.165349` and let us know whether this fixes the issue for you?

Note that you might still see some exceptions being logged:

```
2024-05-14T15:01:41.337Z ERROR 1 --- [   XNIO-1 I/O-3] io.undertow.proxy                        : UT005028: Proxy request to /proxy_endpoint/59db457b-19f3-47e6-8184-05cc519fd470/shared/shiny-showcase.js failed

java.io.IOException: UT001000: Connection closed
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:600) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:535) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]
```

But this does not seem to cause an actual issue. If this fixes the error, I'll look into preventing the exceptions.

**Comment by dylancis** [comment] 2024-05-14 16:36
thanks @LEDfan , will test for sure and revrt to you here.

**Comment by dylancis** [comment] 2024-05-28 15:28
> thanks @LEDfan , will test for sure and revrt to you here.

Hi @LEDfan  how can I get the jar file directly please?

**Comment by LEDfan** [comment] 2024-05-29 13:00
Hi @dylancis you can use the JAR from this link: https://nexus.openanalytics.eu/repository/releases/eu/openanalytics/shinyproxy/3.1.0/shinyproxy-3.1.0-exec.jar

We are looking forward to your testing!

**Comment by dylancis** [comment] 2024-05-29 16:32
> openanalytics/shinyproxy-snapshot:3.1.0-20240514.165349

And this is the same as this one right? openanalytics/shinyproxy-snapshot:3.1.0-20240514.165349

**Comment by LEDfan** [comment] 2024-05-30 07:53
I shared the wrong link, please download the jar from https://nexus.openanalytics.eu/repository/snapshots/eu/openanalytics/shinyproxy/3.1.1-SNAPSHOT/shinyproxy-3.1.1-20240530.074913-1-exec.jar . The version number is different, but it contains the same code as the above docker image.

**Comment by dylancis** [comment] 2024-06-10 11:05
> I shared the wrong link, please download the jar from https://nexus.openanalytics.eu/repository/snapshots/eu/openanalytics/shinyproxy/3.1.1-SNAPSHOT/shinyproxy-3.1.1-20240530.074913-1-exec.jar . The version number is different, but it contains the same code as the above docker image.

Hi @LEDfan , we tried that and got the following error:
![image](https://github.com/openanalytics/shinyproxy/assets/4976433/a6e8ef0f-c6ee-4cce-9dcc-22821493c075)

**Comment by LEDfan** [comment] 2024-06-10 11:16
It seems the container you are using has Java version 8. The latest ShinyProxy release requires Java version 17. It should be easy to change this in the Dockerfile, I just pushed the latest version of our Dockerfile: https://github.com/openanalytics/shinyproxy-docker/blob/master/ShinyProxy/Dockerfile

**Comment by LEDfan** [comment] 2024-06-20 12:11
This is now part of ShinyProxy 3.1.1, which we just released, therefore I'm going to close this issue. Thanks for the report and testing!

**Closed by LEDfan** 2024-06-20 12:11 UTC
Labels: bug
