### ISSUE TITLE
DT ajax error

### ISSUE THREAD

**Issue by templary** [openanalytics/shinyproxy#323] opened 2021-10-14 11:05 UTC
Hello, I would like to ask you for help. 

Im getting  **io.undertow.server.TruncatedResponseException: null** and I have no idea how to fix it.

Im using container proxy 0.8.8 and ShinyProxy 2.5.0

I saw that a similar problem has already been solved here, but unfortunately this solution did not help me.

Thank you a lot

`2021-09-28 13:44:39.179  INFO 13259 --- [  XNIO-1 task-3] c.s.docker.client.DefaultDockerClient    : Starting container with Id: c5674b8a23bd3455ca62a126f6d46c4ddcbdf048cb81976dee8219f2f5b0d46e
22021-09-28 13:44:41.834  INFO 13259 --- [  XNIO-1 task-3] e.o.containerproxy.service.ProxyService  : Proxy activated [user: ____@____.__] [spec: XXXXX] [id: XXXXX]
32021-09-28 13:44:41.908 DEBUG 13259 --- [  XNIO-1 task-3] m.m.a.RequestResponseBodyMethodProcessor : Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json, application/cbor]
42021-09-28 13:44:41.909 DEBUG 13259 --- [  XNIO-1 task-3] m.m.a.RequestResponseBodyMethodProcessor : Writing [{containerPath=/app_direct/xxxx/, proxyId=xxxxxxx}]
52021-09-28 13:44:41.937 DEBUG 13259 --- [  XNIO-1 task-3] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
62021-09-28 13:44:42.144 DEBUG 13259 --- [  XNIO-1 task-3] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
72021-09-28 13:44:42.145 DEBUG 13259 --- [  XNIO-1 task-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
82021-09-28 13:44:42.146 DEBUG 13259 --- [  XNIO-1 task-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
92021-09-28 13:44:42.149 DEBUG 13259 --- [  XNIO-1 task-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
102021-09-28 13:44:42.150 DEBUG 13259 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
112021-09-28 13:44:42.150 DEBUG 13259 --- [  XNIO-1 task-4] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
122021-09-28 13:44:42.216 DEBUG 13259 --- [  XNIO-1 task-4] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
132021-09-28 13:44:42.235 DEBUG 13259 --- [  XNIO-1 task-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
142021-09-28 13:44:42.238 DEBUG 13259 --- [  XNIO-1 task-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
152021-09-28 13:44:42.255 DEBUG 13259 --- [  XNIO-1 task-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
162021-09-28 13:44:42.258 DEBUG 13259 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
172021-09-28 13:44:42.259 DEBUG 13259 --- [  XNIO-1 task-3] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
182021-09-28 13:44:42.396 DEBUG 13259 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
192021-09-28 13:44:42.640 DEBUG 13259 --- [  XNIO-1 task-3] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
202021-09-28 13:44:42.642 DEBUG 13259 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
212021-09-28 13:44:42.643 DEBUG 13259 --- [  XNIO-1 task-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
222021-09-28 13:44:42.800 DEBUG 13259 --- [  XNIO-1 task-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.openanalytics.shinyproxy.controllers.AppController#appDirect(HttpServletRequest, HttpServletResponse)
232021-09-28 13:44:42.894 ERROR 13259 --- [   XNIO-1 I/O-5] io.undertow.proxy                        : UT005028: Proxy request to /proxy_endpoint/a88651a5-0baf-47a2-992b-c45ad9c5f057/session/bbc375cdac1b1d46c1f63b9a888f86b2/dataobj/mytable failed
24
25io.undertow.server.TruncatedResponseException: null
26	at io.undertow.client.http.HttpRequestConduit.truncateWrites(HttpRequestConduit.java:711) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
27	at io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.terminateWrites(AbstractFixedLengthStreamSinkConduit.java:256) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
28	at org.xnio.conduits.ConduitStreamSinkChannel.shutdownWrites(ConduitStreamSinkChannel.java:178) ~[xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
29	at io.undertow.channels.DetachableStreamSinkChannel.shutdownWrites(DetachableStreamSinkChannel.java:79) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
30	at io.undertow.server.handlers.proxy.ProxyHandler$HTTPTrailerChannelListener.handleEvent(ProxyHandler.java:754) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
31	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:646) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
32	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:561) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
33	at io.undertow.client.http.HttpClientExchange.invokeReadReadyCallback(HttpClientExchange.java:212) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
34	at io.undertow.client.http.HttpClientConnection.initiateRequest(HttpClientConnection.java:414) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
35	at io.undertow.client.http.HttpClientConnection.sendRequest(HttpClientConnection.java:347) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
36	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction.run(ProxyHandler.java:561) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
37	at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
38	at io.undertow.server.HttpServerExchange.dispatch(HttpServerExchange.java:821) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
39	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:316) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
40	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:290) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
41	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connectionReady(ProxyConnectionPool.java:353) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
42	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connect(ProxyConnectionPool.java:548) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
43	at io.undertow.server.handlers.proxy.LoadBalancingProxyClient.getConnection(LoadBalancingProxyClient.java:316) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
44	at eu.openanalytics.containerproxy.util.ProxyMappingManager$1.getConnection(ProxyMappingManager.java:88) [containerproxy-0.8.8.jar!/:0.8.8]
45	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:310) [undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
46	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]
47	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]`

**table give this error:**
`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Comment by templary** [comment] 2021-10-21 12:52
Hi @LEDfan 
Thank you for your reply.

I found out that the bug was caused by using params = "action=XXXX" annotation in one of the controllers. 

`@RequestMapping(value = "/XXX/{XXX}/.XXXX", method = RequestMethod.POST,  **params = "action=XXXX"**)`

The controller is not used in any way when running the application but still this error appeared. I can't think of any reason. Do you guys have any reason why this is happening?

**Comment by templary** [comment] 2021-10-21 13:57
Thank you for explanation!

Yes, I modified Java code of ShinyProxy with added controller class
this it whole method:


  ```
  @RequestMapping(value = "xx/{xx}/{xx}/{xx}/{xx}", method = RequestMethod.POST, params = "action=DEACTIVATE")
    private String deactivateRole(ModelMap map, HttpServletRequest request, @PathVariable String xx, @PathVariable String xx, @PathVariable String xx, @PathVariable String xx, @RequestParam(value = "action", required = true) String action) {
        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();

        if (!isAdmin(user)) {
            return "redirect:/error_custom/";
        } else {

            Thread newThread = new Thread(() -> {

          .
          .
          .
          .
          .

            });

            newThread.start();

          .
          .
          .

            return "redirect:/admin_roles_single/" + uid;
        }
    }
```

I will try to do it with GET method.

**Comment by LEDfan** [comment] 2021-11-02 08:43
Nice to heart that the problem is solved now. I'm therefore closing this issue. Feel free to open a new issue if you encounter anything.

**Closed by LEDfan** 2021-11-02 08:43 UTC
