### ISSUE TITLE
shinyapp WebSocket connection Problem

### ISSUE THREAD

**Issue by arafat-sayad** [openanalytics/shinyproxy#358] opened 2022-03-28 06:37 UTC
WebSocket connection Problem 
Dockerfile

FROM rocker/r-base:latest

LABEL maintainer="USER <asayad402@gmail.com>"

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    && rm -rf /var/lib/apt/lists/*
    
RUN R -q -e "install.packages(c('shiny'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinyWidgets'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinydashboard'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinyWidgets'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinymanager'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('DT'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('dplyr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('tidyr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('stringr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('lubridate'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('scales'), repos = 'http://cloud.r-project.org')"
RUN R -e "install.packages('leaflet', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('sf', repos='http://cran.rstudio.com/')"
RUN R -q -e "install.packages(c('plotly'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('gotop'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('highcharter'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('DBI'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('odbc'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('RODBC'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('RPostgreSQL'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('reactable'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('gt'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('writexl'), repos = 'http://cloud.r-project.org')"

RUN apt-get install -y \
    libcurl4-openssl-dev 
RUN mkdir /root/app
COPY ./src /root/app/src
COPY ./data /root/app/data
COPY Rprofile.site /usr/lib/R/etc/

EXPOSE 8080

# CMD Rscript /root/app/src/app.R

CMD ["R", "-e", "shiny::runApp('/root/app/src')"]

application.yml 

proxy:
  title: ShinyProxy
  landing-page: /app/bi-app
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-backend: docker
  authentication: none
  admin-groups: admins
  # Example: 'simple' authentication configuration
  users:
  - name: admin
    password: admin
    groups: admins
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
    # https://bidemo.celloscope.net
  specs:
  - id: bi-app
    description: Demo Banking App
    container-cmd: ["R", "-e", "shiny::runApp('/root/app/src')"]
    container-image: sayad1/bi-app:3.0
    port: 8080
    access-groups: [admins]

logging:
  file:
    name: shinyproxy.log

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

![Screenshot from 2022-03-28 12-31-49](https://user-images.githubusercontent.com/87148404/160339597-8ea05b55-d617-4e4e-ad12-cfbee0013515.png)

**Comment by LEDfan** [comment] 2022-08-08 13:39
Hi

Are you still facing this issue? Typically issues with the websocket connection are caused by reverse proxies or loadbalancers. Can you tell use whether you are using a loadbalancer or reverse proxy? Can you share their configuration as well.

**Comment by LEDfan** [comment] 2024-05-07 14:01
Hi, I think this question has been answered, therefore I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.

**Closed by LEDfan** 2024-05-07 14:01 UTC
Labels: question
