### ISSUE TITLE
Authentification for shinyproxy when using influxdb 

### ISSUE THREAD

**Issue by mostafa790** [openanalytics/shinyproxy#386] opened 2022-09-22 00:39 UTC
Hi, 

I have some issues to run correctly shinyproxy with influxdb.
Shinyproxy works fine without `usages-stats-url` argument but when this argument is added I can not identify.

For the `usages-stats-url` I tried the 2 methods because I'm using the influxdb 2

![image](https://user-images.githubusercontent.com/8080599/181394374-ab3f571c-ff02-4230-b4d6-516319024033.png)

The docker-compose file is like this: 

![image](https://user-images.githubusercontent.com/8080599/181395049-a4bac3c6-30f3-4f91-be3f-ea83e82c77b1.png)

The influxdb container is running with the following command (not included in docker-compose):
`docker run -d --name influxdb -p 8086:8086 -e INFLUXDB_ADMIN_USER=mos -e INFLUXDB_ADMIN_PASSWORD=mos79000 -v /Stats_Publiques/dataspace/influxdb/datas:/var/lib/influxdb --net=app-network influxdb`

Have you some idea about this issue ? Thanks

**Comment by LEDfan** [comment] 2022-10-11 07:20
Hi @mostafa790 

Unfortunately, ShinyProxy does not yet support authentication with influxdb. Because this is a popular feature request, I plan to fix this in the next release (although I cannot guarantee to have it included). I'll close this issue as a duplicate of https://github.com/openanalytics/shinyproxy/issues/225 .

**Closed by LEDfan** 2022-10-11 07:20 UTC
