### ISSUE TITLE
App does not show when using authentication: none

### ISSUE THREAD

**Issue by billy34** [openanalytics/shinyproxy#80] opened 2018-08-14 09:20 UTC
Hello

I'm using version 2.0.1 of shinyproxy

When using `authentication: none`, the app is started correctly (container launched) but nothing is displayed (shinyproxy menubar is displayed but the remaining is blank).

With simple authentication everything works smoothly.

Some error message are in log especially `null pointer exception` in `ProxyMappingManager$MappingOwnerInfo.isSame`

> 2018-08-14 09:07:53.326  INFO 1 --- [ XNIO-3 task-10] c.s.docker.client.DefaultDockerClient    : Starting container with Id: 037ae95293f088f16f54cb49a088430dcdc6c1f99f804fdca51ad7c14ad1c3b0
> 2018-08-14 09:07:56.306  INFO 1 --- [ XNIO-3 task-10] e.o.containerproxy.service.ProxyService  : Proxy activated [user: anonymousUser] [spec: 01_hello] [id: 24217339-ad33-4ad6-9b44-eb6d66c2fed5]
> 2018-08-14 09:07:56.405 ERROR 1 --- [   XNIO-3 I/O-1] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ GET /endpoint/24217339-ad33-4ad6-9b44-eb6d66c2fed5/ request {Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Accept-Language=[fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3], Accept-Encoding=[gzip, deflate], User-Agent=[Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0], Referer=[http://sologne.cirad.fr:8080/app/01_hello], Upgrade-Insecure-Requests=[1], Host=[sologne.cirad.fr:8080]} response HttpServerExchange{ GET /endpoint/24217339-ad33-4ad6-9b44-eb6d66c2fed5/ request {Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Accept-Language=[fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3], Accept-Encoding=[gzip, deflate], User-Agent=[Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0], Referer=[http://sologne.cirad.fr:8080/app/01_hello], Upgrade-Insecure-Requests=[1], Host=[sologne.cirad.fr:8080]} response {}}}
> **java.lang.NullPointerException: null**
>	at eu.openanalytics.containerproxy.util.ProxyMappingManager$MappingOwnerInfo.isSame(ProxyMappingManager.java:125) ~[containerproxy-0.2.1-SNAPSHOT.jar!/:0.2.1-SNAPSHOT]
>	at eu.openanalytics.containerproxy.util.ProxyMappingManager.requestHasAccess(ProxyMappingManager.java:94) ~[containerproxy-0.2.1-SNAPSHOT.jar!/:0.2.1-SNAPSHOT]
>	at eu.openanalytics.containerproxy.ContainerProxyApplication$ProtectedPathHandler.handleRequest(ContainerProxyApplication.java:100) ~[containerproxy-0.2.1-SNAPSHOT.jar!/:0.2.1-SNAPSHOT]
>	at io.undertow.server.handlers.accesslog.AccessLogHandler.handleRequest(AccessLogHandler.java:138) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
>	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
>	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
>	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
>	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

**Comment by dselivanov** [comment] 2018-08-15 07:42
I can confirm this issue. We see the same. Adding basic authorization is workaround we currently use. Also it worked without issues on shinyproxy 1.1.1

**Comment by fmichielssen** [comment] 2018-08-15 11:52
Thanks for the report.

This looks like a bug with the 'none' authentication. When both the authorization header are missing (which is normal in 'none' auth case) and the jsessionid cookie are missing, the nullpointer exception occurs.

**Comment by fmichielssen** [comment] 2018-08-17 14:32
This issue has been fixed in v2.0.2.
If you still encounter the issue, please report back.

**Closed by fmichielssen** 2018-08-17 14:32 UTC
Labels: bug
