### ISSUE TITLE
[Critical bug report] Page objects offset and flickering on newest Chrome 

### ISSUE THREAD

**Issue by Tazovsky** [openanalytics/shinyproxy#139] opened 2019-03-27 22:58 UTC
# Bug description 

Observed critical bug on newest `Google Chrome version 73.0.3683.86 (Official Build) (64-bit)`. 

1. When in full screen app starts flickering - see example:

![shinyproxy-flickering](https://user-images.githubusercontent.com/29068994/55117236-5af3b080-50ea-11e9-892e-43fbf5ac6219.gif)

2. Sometimes when app is not flickering there is some _shift_ between mouse cursor and Shiny app element, for example to click a button user needs to move cursor dozens of pixels down.

# Solution

I fixed that by adding following line:

```
$('#shinyframe').css('margin-top', (1)+'px');
```
in function `setShinyframeHeight`. See https://github.com/Tazovsky/shinyproxy/commit/78f9a2278dc3e64b32b66698466a973f83a919f8.

**Comment by shrektan** [comment] 2019-03-27 23:09
I’ve bite by this two days ago. It’s strange that I haven’t upgraded my Chrome but just tried the new shinyproxy release and revert to the previous version. 

My final solution is a little different, which is set the iframe width to 99% rather than 100%.

**Comment by Tazovsky** [comment] 2019-03-28 07:16
@shrektan our team noticed that bug on multiple versions of ShinyProxy on newest Chrome, but when reverted to older version of Chrome it disappeared.

**Comment by shrektan** [comment] 2019-03-28 08:26
@Tazovsky It's a long story... Various users in my company told me the flickering issues but never be able to reproduce it... It occured occasionally...  and I've never seen this on my computer. 

Until that day, I've tried the new release ShinyProxy... The flickering became reproducible on Chrome... Surprisingly found reverting back to the old version of ShinyProxy didn't help at all... Never been able to understand the root cause. Fortunately, the workaround works.

**Comment by Tazovsky** [comment] 2019-03-28 09:05
@shrektan Unfortunately it have just turned out that my fix causes some DataTable ajax error... can you  send me your code regarding setting iframe to 99%? I'd like to test it.

**Comment by shrektan** [comment] 2019-03-28 10:57
If you are using the latest version of ShinyProxy, it's not your fix leads to the AJAX error. It's a bug of the latest release of ShinyProxy, I believe, see the comment in https://github.com/openanalytics/shinyproxy/issues/137 . 

Should have filed a separate issue but been too busy for the two days...

**Comment by fmichielssen** [comment] 2019-03-29 07:59
The issue has been reported:
https://bugs.chromium.org/p/chromium/issues/detail?id=947038
https://bugs.chromium.org/p/chromium/issues/detail?id=945779
and it looks like a fix is scheduled for the next M73 update of Chrome.

**Comment by moman822** [comment] 2019-04-02 20:06
I have noticed the cursor-offset issue but only when the app creates an element that increases the page height and adds a scrollbar to the page. For example adding a table with many rows to the page.

**Comment by tam0** [comment] 2019-04-15 13:42
I have a similar issue. Here is a reproducible example of the  [Superzip example](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) that is not working properly on Chrome Version 73.0.3683.103. I lose header When I click the show button in the "data explorer" navbar, and then the buttons become unresponsive. I am using shinyproxy2.2.1

App Dockerfile:
`FROM openanalytics/r-base
MAINTAINER Tobias Verbeke "tobias.verbeke@openanalytics.eu"
# system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libssl1.0.0
# system library dependency for the euler app
RUN apt-get update && apt-get install -y \
    libmpfr-dev
# basic shiny functionality
RUN R -e "install.packages(c('shiny', 'rmarkdown'), repos='http://cloud.r-project.org/')"
# install dependencies of the euler app
RUN R -e "install.packages('Rmpfr', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('leaflet', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('scales', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('lattice', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('dplyr', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('RColorBrewer', repos='http://cloud.r-project.org/')"
RUN R -e "install.packages('DT', repos='http://cloud.r-project.org/')"
# copy the app to the image
RUN mkdir /root/euler
COPY . /root/euler
COPY Rprofile.site /usr/lib/R/etc/
EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/root/euler')"]
`

applcation.yml : 
`proxy:
  title: Shinyproxy
  container-wait-time: 60000
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: admin
    groups: admins
  docker:
      internal-networking: true
  specs:
  - id: Superzip
    display-name: Superzip
    description: Description
    #container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: superzip
    container-network: sp-example-net
    access-groups: [admins]
logging:
  file:
    shinyproxy.log
`

shinyproxy Dockerfile : 
`FROM openjdk:8-jre
RUN mkdir -p /opt/shinyproxy/
RUN wget https://www.shinyproxy.io/downloads/shinyproxy-2.2.1.jar -O /opt/shinyproxy/shinyproxy.jar
COPY application.yml /opt/shinyproxy/application.yml
WORKDIR /opt/shinyproxy/
CMD ["java", "-jar", "/opt/shinyproxy/shinyproxy.jar"]`

**Comment by benleen** [comment] 2019-05-02 13:10
Chrome >74 seems to resolve this issue.

**Comment by LEDfan** [comment] 2021-07-30 13:11
As I believe that your question is answered (since the issue is solved in Chrome), I'm closing this issue. Feel free to re-open it if you need more help.

**Closed by LEDfan** 2021-07-30 13:11 UTC
