### ISSUE TITLE
No loading message when /app_direct/ Shiny App is launched (contrary to /app/ version)

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#159] opened 2019-06-19 09:06 UTC
The `/app_direct/` verion of the Shiny Application does not show the loading message in contrary to the `/app/` version.

`/app/`:
![image](https://user-images.githubusercontent.com/4976433/59612425-f8241b00-9114-11e9-8bd4-a877cff64843.png)

The time it takes to load the application is the same, but while `/app/ `shows you the following message, the `/app_direct/` will not show anything until the application loads up.

`/app_direct/`:
![image](https://user-images.githubusercontent.com/4976433/59612223-a1b6dc80-9114-11e9-963d-4c27cd90404d.png)

Is there any reason for now showing the startup message in `/app_direct/` ?

Thank, you, Dylan

**Comment by dylancis** [comment] 2019-06-27 08:12
This is even a bigger problem when a new pod is spinning up where a few minute can be spent waitring for the container to be ready.

**Comment by kuzmenkov111** [comment] 2019-10-02 16:15
Is any news about this problem?

**Comment by tanho63** [comment] 2019-11-22 16:31
The /app/ version is an HTML page created from the [app.html template](https://github.com/openanalytics/shinyproxy/blob/master/src/main/resources/templates/app.html) - the loading screen is a javascript call from that template. The /app_direct/ version is the raw shiny app, which is then iframed into the /app/ template. 

You might consider other loading screen methods like: https://stackoverflow.com/questions/35599470/shiny-dashboard-display-a-dedicated-loading-page-until-initial-loading-of

**Comment by LEDfan** [comment] 2021-03-03 08:18
Hi all

It's indeed correct that no loading screen is shown when using the `app_direct` endpoint, this is the intended behavior. The idea of this endpoint is to integrate it in some other application and then also create your own loading page.
Since ShinyProxy 2.5.0, you can now also load an application with the `sp_hide_navbar=true` query parameter. For example:
```
http://localhost:8080/app/rstudio?sp_hide_navbar=true
```
This still uses an iframe to load the application and therefore also displays the loading animation, however, the navigation bar is hidden. I hope this option is a good alternative for the `app_direct` endpoint.

Since I think this issue is solved now, I'm closing it. Feel free to open a new issue if you encounter any problem.

**Closed by LEDfan** 2021-03-03 08:18 UTC
Labels: question
