### ISSUE TITLE
FEATURE REQUEST: Generic User / Password

### ISSUE THREAD

**Issue by jtelleriar** [openanalytics/shinyproxy#296] opened 2021-05-12 08:43 UTC
First of all, thank you all for your excellent work with ShinyProxy!

As a feature request:

We might have scenarios in which we would like to have a generic user (User / Password), which is shared across multiple persons, and these have the chance to connect simultaneously to ShinyProxy Applications.

For example: 

- Imagine one co-worker does not have its Microsoft Active Directory User Created yet (Or has issues connecting with his corporate user), in those cases, we would like to share 1 user for multiple persons (In a way, that they do not overlap each other, through simultaneous connections to the same app).

Thank you in advance!

**Comment by tverbeke** [comment] 2021-05-12 09:20
Hi @jtelleriar 

I don't think this is something that would be good to solve at the ShinyProxy level:  if this is a requirement, you could ask to create a permanent user in AD for this purpose only and then manage it as you say.

Kind regards,
Tobias

**Comment by jtelleriar** [comment] 2021-05-12 17:07
Thank you Tobias for your feedback.

The motivation of my request is that, even if we have this generic AD user, if this is used say, an app is used by 2 persons simultaneously, the would be working within the same Docker container, and it would be better to spin off 2 containers.

**Comment by LEDfan** [comment] 2021-05-17 06:49
I understand your use-case. However, currently this really goes against the current design of ShinyProxy. It's by design that an user can only run one instance of every app. Without this limitation it would become much harder to manage the different instances of apps. We can keep this issue open as a feature-request but I'm afraid that we won't solve this in the near-future. Maybe if other users have similar requests, we can spend some time on this.

**Comment by jtelleriar** [comment] 2021-05-17 13:21
For this "generic shared user" maybe a random ID could be mapped, only under those scenarios in which within the application.yml file, such "feature" is enabled because, as you pointed out, not everybody may need it.

Thank you in advance!

**Comment by michaelhogersnplm** [comment] 2021-05-17 13:48
@jtelleriar a hacky solution might be to create multiple specs with different id's but using the same docker image

**Comment by jtelleriar** [comment] 2021-05-17 16:12
@michaelhogersnplm jajajjaa But the suggestion is about not being Hacky, and having an official way of doing it from the .yml ;) 

Thank you for your proposal however Michael,

Regards,
Juan

**Comment by LEDfan** [comment] 2021-11-05 15:25
Hi @jtelleriar 

[ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10) now supports opening multiple instances of a single app. 
See the docs here: https://shinyproxy.io/documentation/ui/#using-multiple-instances-of-an-app

I think this should solve you problem, therefore I'm closing this issue. If it doesn't solve your issue completely, feel free to re-open it.

**Closed by LEDfan** 2021-11-05 15:25 UTC
Labels: enhancement
