### ISSUE TITLE
Blocked loading mixed active content after some times

### ISSUE THREAD

**Issue by AMillanFL** [openanalytics/shinyproxy#394] opened 2022-12-08 14:41 UTC
Hello,
On my shiny app, in a tab I use leaflet map and font awesome script. 
If I go on the tab after loading the app all the external scripts and files are load perfectly.
If I wait some minutes, the map and font scripts didn't load with :

`Blocked loading mixed active content “http://myshinyproxy.com/login”
The resource from “https://myshinyproxy.com/app_direct/reporting_general/leaflet-awesomemarkers-2.0.3/leaflet.awesome-markers.css” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff).
`

Looks like I lost the login certification.

The authentification is : simple.
Is it something to do with heartbeat rate and timeout ?
Is there a parameter allowing to avoid or extend this time limitation ?

Thanks

**Comment by LEDfan** [comment] 2023-03-06 10:22
Hi, this could be caused by both the session timeout and the hearbteat timeout mechanisms. However, if the app is used by the user, ShinyProxy should not stop the application or log out the user. Most apps either open a websocket connection or regularly (at least every ~minute) make a HTTP request and then the app stays active. If it doesn't do this, ShinyProxy send fallback hearbeats. However, this did not work in all situations, this was fixed in ShinyProxy 3.0.0.

Could you please try with ShinyProxy 3.0.0?

**Comment by LEDfan** [comment] 2024-05-07 13:55
Hi, I think this question has been answered, therefore I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.

**Closed by LEDfan** 2024-05-07 13:55 UTC
Labels: bug
