### ISSUE TITLE
Error status code 200 while hitting landing-page of ShinyProxy

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#158] opened 2019-06-17 14:32 UTC
initial comment moved to a separate ticket #159

**Comment by dylancis** [comment] 2019-06-18 12:37
I believe this is also the reason why if you try top freshly open the `/app__direct/` while using auth0, afterlogin, you will get straight the following page:

![image](https://user-images.githubusercontent.com/4976433/59682449-34678200-91ce-11e9-96e9-ab14e2b792ef.png)

You git F5 (refresh) anfd the app will show up.

**Comment by michaelhogersosis** [comment] 2019-06-18 13:09
We are using `landing-page: /app_direct/<app-name>/` + Auth0 and users occassionally see the 200 error mentioned by @dylancis.

**Comment by dylancis** [comment] 2019-06-18 13:22
@michaelhogersosis we are using the default `landing-page` in our side.

**Comment by dylancis** [comment] 2019-06-19 08:16
This is happening even using the main index page and clicking on the app link without `/app_direct/`

**Comment by michaelhogersosis** [comment] 2019-06-19 09:00
@dylancis, do you occasionally have users running into a 404 error as well? It is similar to the 200 error you describe, in that the application will show up after refreshing the page

**Comment by dylancis** [comment] 2019-06-19 09:01
@michaelhogersosis  I used to indeed  after a new deployement - now our process tries the app once after a new ShinyProxy deployment.

**Comment by dylancis** [comment] 2019-06-19 09:04
HI @fmichielssen I have renamed the github issue as this was two different issues one is feature request:
- loader screen meesage while `/addp_direct/` is launched
- 200 error status code while loading landing page of ShinyProxy (the one here)

**Comment by michaelhogersosis** [comment] 2019-06-19 09:04
@dylancis, interesting, we noticed a similar issue after a new deployment. Are you using Kubernetes? I had a feeling our `image-pull-policy: Always` setting was the cause

**Comment by dylancis** [comment] 2019-06-19 09:11
@michaelhogersosis  yes we do use k8s although we have the following set:
`image-pull-policy: IfNotPresent`

**Comment by ericwburden** [comment] 2019-09-09 19:45
I have a user at another site who runs into this the first time they attempt to log in on a regular basis. I'm not using k8s, but I am using KeyCloak for authentication. Not using the /app-direct/ URL, either.

**Comment by PauloJhonny** [comment] 2021-05-26 20:54
I have the same issue when i try to login the first time. The second time works well and i can access the main apps page.
I'm using LDAP for authentication. (I'm not using the k8s and /app-direct/ URL).

Error print:

![image](https://user-images.githubusercontent.com/14023635/119729579-33740c00-be4b-11eb-91da-d5e0169802f7.png)

**Comment by tverbeke** [comment] 2021-05-27 06:01
Hi @PauloJhonny Can you check with ShinyProxy 2.5.0? 2.3.0 is almost two years old and there have been 6 releases since (with numerous fixes).

**Comment by PauloJhonny** [comment] 2021-05-27 13:35
Hi @tverbeke. I'm having a problem when upgrading to 2.5.0 :( 
That's why i haven't done it yet.
If i just change Dockerfile to get the 2.5.0 version, I can access the login page, but it is not responsive...

Since i customized shinyproxy templates (app.html, index.html, login.html, navbar.html), i think there's something to do with it... where can i have access to the templates of shinyproxy 2.5.0? Maybe I need to do the customization again, but using the default template files.

Thank you.

**Comment by LEDfan** [comment] 2021-07-30 13:09
Hi @PauloJhonny 

Great to hear that 2.5.0 solved your issue!
As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.

**Closed by LEDfan** 2021-07-30 13:09 UTC
